const menuOptions = [
    { name: 'X-Salada', price: 30, vegan: false, src: './img/xsalada.ed.jpeg' },
    { name: 'X-Bacon', price: 34, vegan: false, src: './img/xbacon.ed.png' },
    { name: 'X-Bacon Egg', price: 39, vegan: false, src: './img/bacon-egg.ed.png' },
    { name: 'Monstruoso', price: 50, vegan: false, src: './img/monstruoso.ed.png' },
    { name: 'Big Vegano', price: 55, vegan: true, src: './img/xvegan.ed.png' },
    { name: 'X-Vegan', price: 45, vegan: true, src: './img/monstruoso-vegan.ed.png' },
    { name: 'X-salada', price: 23 , vegan: true, src: './img/xsalada.ed.jpg'},
    { name: 'X-salada-verde', price: 28 , vegan: true, src: './img/xsaladaverde.ed.jpg'},
    { name: 'X-cheder', price: 35 , vegan: false, src: './img/xcheder (5).ed.jpg' },
    { name: 'X-cheder-duplo', price: 48 , vegan: false, src: './img/xcheder.ed.jpg'},
    { name: 'X-frango', price: 70 , vegan: false, src: './img/xfrango.ed.jpg'},
    { name: 'X-tudo', price: 40 , vegan: false , src: './img/xtudo.ed.jpg'},
    { name: 'X-Alegre', price: 48 , vegan: true , src: './img/saladaalegre.ed.jpg'},
    { name: 'X-Calabresa', price: 50 , vegan: false , src: './img/xcalabresa.ed.jpg'},
    { name: 'x4queijos', price: 60 , vegan: false , src: './img/x54queijo.ed.jpg'},
    { name: 'X-Camarão', price: 25 , vegan: false , src: './img/xcamarao.ed.jpg'},
    { name: 'X-Cebola', price: 20 , vegan: false , src: './img/xcebola.ed.jpg'},
    { name: 'X-combo', price: 15 , vegan: false , src: './img/xcompo.ed.jpg'},
    { name: 'X-Familia', price: 35 , vegan: false , src: './img/xfamilia.ed.jpg'},
    { name: 'X-Médio', price: 19 , vegan: false , src: './img/xmedio.ed.jpg'},
    { name: 'X-mini', price: 27 , vegan: false , src: './img/xmini.ed.jpg'},
    { name: 'X-salada-mista', price: 45 , vegan: true , src: './img/xsaladamista.ed.jpg'},
    { name: 'X-Tradicional', price: 35 , vegan: false , src: './img/xtradicional.ed.jpg'},
    { name: 'X-Triplo', price: 50 , vegan: false , src: './img/xtriplo.ed.jpg'},
  ]
  